### ISSUE TITLE
UCloud maintainer requirement

### ISSUE THREAD

**Issue by fioncat** [ucloud/packer-plugin-ucloud#50]
Hi, I am a developer from ucloud, we need to do some bug fixes to this repo recently.

Now we donot have any maintainer under this repo, I would like to ask what steps are required to apply for the maintainer permission? So that we can do bug fixes more convenient and opportune.

@azr @nywilken

**Comment by nywilken** [comment]
Hi @fioncat apologies for not being able to get to this question sooner. We are excited to have you and the UCloud team maintain this plugin. We can not grant you maintainer permission into the HashiCorp GitHub org. But I would like to speak with you about transferring the plugin to your GitHub org so that your team can manage and release the plugin like you do for the Terraform provider. 

I have a contact email for this request that came through our support channel. I will follow up there with details on what the transfer process looks like and possible next steps.

**Comment by schnell18** [comment]
> Hi @fioncat apologies for not being able to get to this question sooner. We are excited to have you and the UCloud team maintain this plugin. We can not grant you maintainer permission into the HashiCorp GitHub org. But I would like to speak with you about transferring the plugin to your GitHub org so that your team can manage and release the plugin like you do for the Terraform provider.
> 
> I have a contact email for this request that came through our support channel. I will follow up there with details on what the transfer process looks like and possible next steps.

Thanks a million to @nywilken, after some trials and errors, I finally figure out to transfer the ownership the `packer-plugin-ucloud` to UCloud and the new release v1.0.6, followed by v1.0.7 to resolve the HCL issue, has been created to mark this change.
